# See https://pre-commit.com for more informations
# See https://pre-commit.com/hooks.html for more hooks
default_language_version:
  python: python3
repos:
- repo: https://github.com/timothycrosley/isort
  rev: 5.10.1
  hooks:
  - id: isort
    name: Sort imports
    description: Sort python imports
- repo: https://github.com/psf/black
  rev: 22.6.0
  hooks:
  - id: black
    name: Format with black
    description: General python formatter
    language_version: python3
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-docstring-first
  - id: mixed-line-ending
  - id: check-builtin-literals
  - id: check-ast
  - id: check-toml
  - id: check-json
  - id: pretty-format-json
    args: ["--no-sort-keys","--autofix"]
  - id: check-merge-conflict
  - id: check-case-conflict
- repo: https://github.com/jendrikseipp/vulture
  rev: v2.4
  hooks:
  - id: vulture
    name: Check for unused code
    description: Find dead python code
- repo: https://github.com/pycqa/flake8
  rev: 4.0.1
  hooks:
  - id: flake8
    name: Validate python code (PEP8)
    description: Lint code against PEP8 coding standards
- repo: local
  hooks:
  - id: unittest
    name: Runs unit tests
    entry: python -m unittest discover
    language: system
    types: [python]
    stages: [commit]
    pass_filenames: false
